var lyrics = [
        "<p>\"I hate the winter in Lexington / I hate the winter in Lexington\"</p><h6>-Dashboard Confessional, 'Age Six Racer'</h6>",
        "<p>\"So long sweet summer / I stumbled upon you and gratefully basked in your rays\"</p><h6>-Dashboard Confessional, 'Age Six Racer'</h6>",
        "<p>\"It's colder than it ought to be in March / And I've still got a day or two ahead of me / 'Till I'll be heading home, into your arms again\"</p><h6>-Dashboard Confessional, 'A Plain Morning'</h6>",
        "<p>\"Staring into the sun / We eat our young / This can't be what you're waiting for\"</p><h6>-Abandoned Pools, 'Blood'</h6>",
        "<p>\"I'm stuck in a coma / Stuck in a never ending sleep / Someday I will wake up / And realize I made up everything\"</p><h6>-Senses Fail, 'Can't Be Saved'</h6>",
        "<p>\"Sail with me into the setting sun / The battle has been won, but war has just begun\"</p><h6>-Senses Fail, 'Rum is for Drinking, Not for Burning'</h6>",
        "<p>\"Do you, do you like dreaming / Of things so impossible? / Or only the practical, / or ever the wild?\"</p><h6>-Dashboard Confessional, 'So Impossible'</h6>",
        "<p>\"On the way home, this car hears my confessions / I think tonight I'll take the long way home\"</p><h6>-Dashboard Confessional, 'The Sharp Hint of New Tears'</h6>",
        "<p>\"My hopes are so high that your kiss might kill me / So won't you kill me, / so I die happy?\"</p><h6>-Dashboard Confessional, 'Hands Down'</h6>",
        "<p>\"Out on the road today, I saw a Deadhead sticker on a Cadillac\"</p><h6>-Don Henley, 'The Boys of Summer'</h6>",
        "<p>\"Your hair, it's everywhere / Screaming infidelities and taking its wear\"</p><h6>-Dashboard Confessional, 'Screaming Infidelities'</h6>",
        "<p>\"And breathing is a foreign task / And thinking's just too much to ask / And you're measuring your minutes by a clock that's blinking eights\"</p><h6>-Dashboard Confessional, 'The Brilliant Dance'</h6>",
        "<p>\"Our sidestepping has come to be a brilliant dance / Where nobody leads at all\"</p><h6>-Dashboard Confessional, 'The Brilliant Dance'</h6>",
        "<p>\"Goodness knows I saw it coming / Or at least, I'll claim I did / But in truth I'm lost for words\"</p><h6>-Snow Patrol, 'Chocolate'</h6>",
        "<p>\"Don't it always seem to go / That you don't know what you got 'till it's gone\"</p><h6>-Counting Crows, 'Big Yellow Taxi'</h6>",
        "<p>\"Merry Christmas, Merry Christmas / But I think I'll miss this one this year\"</p><h6>-The Waitresses, 'Christmas Wrapping'</h6>",
        "<p>\"And so I cry sometimes when I'm lying in bed / Just to get it all out, what's in my head / And I, I am feeling a little peculiar\"</p><h6>-4 Non Blondes, 'What's Up?'</h6>",
        "<p>\"I can see where I am going to be / When the reaper reaches and touches my hand\"</p><h6>-Arcade Fire, 'Wake Up'</h6>",
        "<p>\"What a mess our lives turned out to be / It was at its best when you and I were only three\"</p><h6>-Abandoned Pools, 'Start Over'</h6>",
        "<p>\"So take the photographs and still frames in your mind / Hang it on a shelf in good health and good time\"</p><h6>-Green Day, 'Good Riddance (Time of Your Life)'</h6>",
        "<p>\"Then you can be the remedy / And I can be the enemy / And he can go and live as nothing\"</p><h6>-Abandoned Pools, 'The Remedy'</h6>",
        "<p>\"And if a double-decker bus / Crashes into us / To die by your side is such a heavenly way to die\"</p><h6>-The Smiths, 'There Is a Light That Never Goes Out'</h6>",
        "<p>\"With auburn hair and tawny eyes / The kind of eyes that hypnotize me through\"</p><h6>-A Flock of Seagulls, 'I Ran (So Far Away)'</h6>",
        "<p>\"Jealousy, turning saints into the sea / Swimming through sick lullabies, choking on your alibis\"</p><h6>-The Killers, 'Mr. Brightside'</h6>",
        "<p>\"I know I felt like this before / But now I'm feeling it even more / Because it came from you\"</p><h6>-The Cranberries, 'Dreams'</h6>",
        "<p>\"Penny Lane is in my ears and in my eyes / There beneath the blue suburban skies / I sit and meanwhile back...\"</p><h6>-The Beatles, 'Penny Lane'</h6>",
        "<p>\"Keep your head still / I'll be your thrill / The night will go on / My little windmill\"</p><h6>-blink-182, 'All the Small Things'</h6>",
        "<p>\"I struggle for the words and then give up / My head's up with the birds on the t-hut\"</p><h6>-Snow Patrol, 'Spitting Games'</h6>",
        "<p>\"A little peace of mind that I know better / Than the plain disgrace of all my letters\"</p><h6>-Snow Patrol, 'Spitting Games'</h6>",
        "<p>\"Lonely written words for company / Just raise the roof this once and follow me\"</p><h6>-Snow Patrol, 'Spitting Games'</h6>",
        "<p>\"You've already won me over in spite of me / And don't be alarmed if I fall head over feet\"</p><h6>-Alanis Morissette, 'Head over Feet'</h6>",
        "<p>\"I'm dreaming / That you're in love with me / Like I'm in love with you / But dreaming's all I do / If only they'd come true\"</p><h6>-Kylie Minogue, 'I Should Be So Lucky'</h6>",
        "<p>\"You've got me wrapped around your finger / Do you have to let it linger?\"</p><h6>-The Cranberries, 'Linger'</h6>",
        "<p>\"I'm waiting for blood to flow to my fingers / I'll be alright when my hands get warm\"</p><h6>-Dashboard Confessional, 'The Best Deceptions'</h6>",
        "<p>\"And you'll be sorry / Isn't that what they'll say? / Don't follow your heart 'cause it just seems to get in your way\"</p><h6>-Dashboard Confessional, 'Drowning'</h6>",
        "<p>\"There's an obvious attraction to the path of least resistance / In your life\"</p><h6>-Alanis Morissette, 'Wake Up'</h6>",
        "<p>\"There used to be a reason why / We wrote the words across the sky / You and I will never die without a fight / My suburban muse\"</p><h6>-Abandoned Pools, 'Suburban Muse'</h6>",
        "<p>\"A certain callousness complies / With your charm and in your pride / A hopeful look draped in despise\"</p><h6>-Dashboard Confessional, 'Ender Will Save Us All'</h6>",
        "<p>\"Talk is cheap, and it doesn't mean much / Don't lose touch, don't lose touch\"</p><h6>-Against Me!, 'Don't Lose Touch'</h6>",
        "<p>\"And all the roads we have to walk are winding / And all the lights that lead us there are blinding\"</p><h6>-Oasis, 'Wonderwall'</h6>",
        "<p>\"I wouldn't trade one stupid decision / For another five years of life\"</p><h6>-LCD Soundsystem, 'All My Friends'</h6>",
        "<p>\"Well your mind is there but your heart is out to lunch / And it's all because your philosophy's just a hunch\"</p><h6>-Abandoned Pools, 'Never'</h6>",
        "<p>\"And the frightening facts we've been facing our backs to for so long now / Are begging for eyes to bear witness to lies and indifference\"</p><h6>-Dashboard Confessional, 'Turpentine Chaser'</h6>",
        "<p>\"Didn't have to say my name / Ignite my circuits, start a flame\"</p><h6>-Steam Powered Giraffe, 'Honeybee'</h6>",
      ];
      
      document.getElementById('randomLyricGenerator').innerHTML = lyrics[Math.floor(Math.random()*lyrics.length)];